---
title: "More resources"
format: html
---


TNA has been presented for the first time at the Learning Analytics & Knowledge conference (LAK) 2025.

- Mohammed Saqr, Sonsoles López-Pernas, Tiina Törmänen, Rogers Kaliisa, Kamila Misiejuk, and Santtu Tikka. 2025. Transition Network Analysis: A Novel Framework for Modeling, Visualizing, and Identifying the Temporal Patterns of Learners and Learning Processes. In Proceedings of the 15th International Learning Analytics and Knowledge Conference (LAK ’25). Association for Computing Machinery, New York, NY, USA, 351–361. <https://doi.org/10.1145/3706468.3706513>

TNA can be implemented using the R package of the same name, available on CRAN:

- Mohammed Saqr, Santu Tikka, Sonsoles López-Pernas (2024). *tna: An R package for Transition Network Analysis*. R package version 0.4.0, <https://github.com/sonsoleslp/tna>.

The reference manual is available in <https://sonsoles.me/tna>

There are three R tutorials available about TNA:

- **Basic tutorial**: Mohammed Saqr, Sonsoles López-Pernas, Santtu Tikka (2025). *Mapping Relational Dynamics with Transition Network Analysis: A Primer and Tutorial*. In M. Saqr & S. López-Pernas (Eds.), Advanced Learning Analytics Methods: AI, Precision and Complexity (in – press). Springer. <https://lamethods.org/book2/chapters/ch15-tna/ch15-tna.html>
- **Frequency-based TNA**: Mohammed Saqr, Sonsoles López-Pernas, Santtu Tikka (2025). *Capturing The Breadth and Dynamics of the Temporal Processes with Frequency Transition Network Analysis: A Primer and Tutorial*. In M. Saqr & S. López-Pernas (Eds.), Advanced Learning Analytics Methods: AI, Precision and Complexity (in – press). Springer. <https://lamethods.org/book2/chapters/ch16-ftna/ch16-ftna.html>
- **Clustering**: Sonsoles López-Pernas, Santtu Tikka, Mohammed Saqr (2025). *Mining Patterns and Clusters with Transition Network Analysis: A Heterogeneity Approach*. In M. Saqr & S. López-Pernas (Eds.), Advanced Learning Analytics Methods: AI, Precision and Complexity (in – press). Springer. <https://lamethods.org/book2/chapters/ch17-tna-clusters/ch17-tna-clusters.html>

Stay tuned to find out all new developments!